---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.secretname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    global:
      evaluation_interval: 5s
      external_labels:
        source: promxy
    remote_write:
      - url: {{ .Values.promxy.config.remoteWriteUrl | default | quote }}
    promxy:
      server_groups: []
