{{- if eq .Values.promxy.secret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.secretname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- if .Values.promxy.extraLabels }}
    {{ toYaml .Values.promxy.extraLabels | nindent 4 }}
    {{- end }}
stringData:
  config.yaml: |
    global:
      evaluation_interval: 5s
      external_labels:
        source: promxy
    remote_write:
      - url: {{ .Values.promxy.config.remoteWriteUrl | default | quote }}
    promxy:
      server_groups:
        {{- range .Values.promxy.config.serverGroups }}
        - static_configs:
            - targets:
              {{- range .targets }}
              - {{ . | quote }}
              {{- end }}
          path_prefix: {{ .pathPrefix | default "/vm/select/0/prometheus/" | quote }}
          scheme: {{ .scheme | default "https" | quote }}
          http_client:
            dial_timeout: {{ .dialTimeout | default "1s" | quote }}
            tls_config:
              insecure_skip_verify: true
            basic_auth:
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .auth.credentials_secret_name) }}
{{- if $secret }}
              username: {{ index $secret.data (.auth.username_key | default "GF_SECURITY_ADMIN_USER") | b64dec | quote }}
              password: {{ index $secret.data (.auth.password_key | default "GF_SECURITY_ADMIN_PASSWORD") | b64dec | quote }}
{{- end }}
          labels:
            promxyCluster: {{ .clusterName | quote }}
        {{- end }}
{{- end }}
