global:
  clusterLabel: clusterName
  storageClass: standard
  clusterName: mothership
hmc:
  installTemplates: false
  motel:
    repo:
      name: motel
      url: https://mirantis.github.io/motel/
      insecure: false
      type: "default"
    charts:
      operators:
        version: 0.0.1
      collectors:
        version: 0.0.1
      storage:
        version: 0.1.2
victoriametrics:
  enabled: true
  vmcluster:
    enabled: true
    replicationFactor: 1
    replicaCount: 1
  vmalert:
    enabled: true
    remoteRead: ""
grafana:
  enabled: true
  ingress:
    enabled: false
    host: grafana.example.net
  alerts:
    enabled: true
  logSources:
    - name: hmc0-logs
      url: https://vmauth.hmc0.example.net/vls
      type: victoriametrics-logs-datasource
      auth:
        credentials_secret_name: grafana-admin-credentials
    - name: hmc1-logs
      url: https://vmauth.hmc1.example.net/vls
      type: victoriametrics-logs-datasource
      auth:
        credentials_secret_name: grafana-admin-credentials
  security:
    credentials_secret_name: grafana-admin-credentials
victoria-metrics-operator:
  enabled: true
  crds:
    plain: true
cluster-api-visualizer:
  enabled: true
promxy:
  replicaCount: 1
  enabled: true
  image:
    repository: quay.io/jacksontj/promxy
    tag: "latest"
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
    annotations: {}
    # If not set, generated using the fullname template
    name:
  service:
    type: ClusterIP
    enabled: true
    servicePort: 8082
    annotations: {}
    extraLabels: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations: {}
    extraLabels: {}
    path: /
    pathType: Prefix
    hosts:
      - example.com
    tls: []
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
  extraArgs:
    log-level: "info"
  secret: ""
  config:
    remoteWriteUrl: http://vminsert-cluster:8480/insert/0/prometheus/api/v1/write
    serverGroups:
      - clusterName: hmc0
        targets:
          - vmauth.hmc0.example.net:443
        auth:
          credentials_secret_name: grafana-admin-credentials
      - clusterName: hmc1
        targets:
          - vmauth.hmc1.example.net:443
        auth:
          credentials_secret_name: grafana-admin-credentials
