{{- if .Values.kcm.installTemplates }}
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: cert-manager
  namespace: {{ .Values.kcm.namespace }}
spec:
  helm:
    chartRef:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmChart
      name: cert-manager
      namespace: {{ .Values.kcm.namespace }}
  providers: []
{{- end }}
