apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-storage0
  namespace: kcm-system
  labels:
    kof: "storage"
spec:
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: kcm-system
    controlPlane:
      instanceType: t3.large
    controlPlaneNumber: 1
    publicIP: true
    region: us-east-2
    worker:
      instanceType: t3.medium
    workersNumber: 3
    clusterLabels:
      k0rdent.mirantis.com/kof-storage-secrets: "true"
      k0rdent.mirantis.com/kof-aws-dns-secrets: "true"
  template: aws-standalone-cp-0-0-5
  serviceSpec:
    priority: 100
    services:
      - template: ingress-nginx-4-11-3
        name: ingress-nginx
        namespace: ingress-nginx
      - name: cert-manager
        namespace: cert-manager
        template: cert-manager
        values: |
          crds:
            enabled: true
      - name: kof-storage
        namespace: kof
        template: kof-storage
        values: |
          victoriametrics:
            vmauth:
              ingress:
                host: vmauth.storage0.example.net
            security:
              username_key: username
              password_key: password
              credentials_secret_name: storage-vmuser-credentials
          grafana:
            ingress:
              host: vmauth.storage0.example.net
            security:
              credentials_secret_name: grafana-admin-credentials
          cert-manager:
            email: mail@example.net
