apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: aws-storage0
  namespace: hmc-system
  labels:
    kof: "storage"
spec:
  credential: aws-cluster-identity-cred
  config:
    clusterIdentity:
      name: aws-cluster-identity
      namespace: hmc-system
    controlPlane:
      instanceType: t3.large
    controlPlaneNumber: 1
    publicIP: true
    region: us-east-2
    worker:
      instanceType: t3.medium
    workersNumber: 3
  template: aws-standalone-cp-0-0-4
  servicesPriority: 100
  services:
    - template: ingress-nginx-4-11-3
      name: ingress-nginx
      namespace: ingress-nginx
    - name: cert-manager
      namespace: cert-manager
      template: cert-manager
      values: |
        crds:
          enabled: true
    - name: kof-storage
      namespace: kof
      template: kof-storage
      values: |
        victoriametrics:
          vmauth:
            ingress:
              host: vmauth.storage0.example.net
          security:
            password_secret_name: grafana-admin-credentials
            password_key: "GF_SECURITY_ADMIN_PASSWORD"
        grafana:
          ingress:
            host: grafana.storage0.example.net
          security:
            credentials_secret_name: grafana-admin-credentials
        cert-manager:
          email: mail@example.net
