{{- if index .Values "grafana" "enabled" | default false }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: agg-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  datasource:
    access: proxy
    isDefault: false
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: agg-prometheus
    type: prometheus
    url: http://vmselect-cluster:8481/select/0/prometheus
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 5m
{{- end }}