{{- if .Values.grafana.enabled }}
{{- range .Values.grafana.logSources }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  datasource:
    access: proxy
    isDefault: false
    name: {{ .name }}
    type: {{ .type | default "victoriametrics-logs-datasource " }}
    url: {{ .url }}
    basicAuth: true
    basicAuthUser: {{ .auth.username | quote }}
    secureJsonData:
      basicAuthPassword: {{ .auth.password | quote }}
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 5m
---
{{- end }}
{{- end }}