{{- if index .Values "fluent-bit" "enabled" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vl-outputs
  namespace: {{ .Release.Namespace }}
data:
  output_vl.conf: |
    [OUTPUT]
      Name             http
      Match            kube.*
      Host             {{ index .Values "fluent-bit" "outputHost" }}
      URI              {{ index .Values "fluent-bit" "outputURI" | default "/vls/insert/jsonline" }}
      port             443
      tls              on
      compress         gzip
      format           json_lines
      json_date_format iso8601
      http_User        {{ index .Values "fluent-bit" "outputUsername" }}
      http_Passwd      {{ index .Values "fluent-bit" "outputPassword" }}
      header           AccountID 0
      header           ProjectID 0
      header           VL-Msg-Field log
      header           VL-Time-Field date
      header           VL-Stream-Fields stream,kubernetes_pod_name,kubernetes_container_name,kubernetes_namespace_name
{{- end }}