{{- if (index .Values "victoriametrics" "vmagent" | default dict).enabled | default false }}
apiVersion: v1
kind: Secret
metadata:
  name: vmauth-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.victoriametrics.vmagent.remoteUsername | default "motel" | quote }}
  password: {{ .Values.victoriametrics.vmagent.remotePassword | default "motel" | quote }}
{{- end }}