{{- if .Values.grafana.security.create_secret }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.grafana.security.credentials_secret_name) }}
{{- if not $secret }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.grafana.security.credentials_secret_name }}
  namespace: {{ .Release.Namespace }}
stringData:
  GF_SECURITY_ADMIN_USER: {{ randAlpha  (.Values.global.random_username_length | int) | quote }} # Grafana username
  GF_SECURITY_ADMIN_PASSWORD: {{ randAlpha (.Values.global.random_password_length | int) | quote }} # Grafana password
type: Opaque
{{- end }}
{{- end }}
