export const METRICS = {
  OTEL_SCOPE_INFO: "otel_scope_info",
  OTELCOL_EXPORTER_PROM_WRITE_CONSUMERS: "otelcol_exporter_prometheusremotewrite_consumers",
  OTELCOL_EXPORTER_PROM_WRITE_SENT_BATCHES: "otelcol_exporter_prometheusremotewrite_sent_batches_total",
  OTELCOL_EXPORTER_PROM_WRITE_TRANS_RATIO: "otelcol_exporter_prometheusremotewrite_translated_time_series_ratio_total",
  OTELCOL_EXPORTER_QUEUE_CAPACITY: "otelcol_exporter_queue_capacity",
  OTELCOL_EXPORTER_QUEUE_SIZE: "otelcol_exporter_queue_size",
  OTELCOL_EXPORTER_SEND_FAILED_LOG_RECORDS: "otelcol_exporter_send_failed_log_records_total",
  OTELCOL_EXPORTER_SEND_FAILED_METRIC_POINTS: "otelcol_exporter_send_failed_metric_points_total",
  OTELCOL_EXPORTER_SENT_LOG_RECORDS: "otelcol_exporter_sent_log_records_total",
  OTELCOL_EXPORTER_SENT_METRIC_POINTS: "otelcol_exporter_sent_metric_points_total",
  OTELCOL_FILECONSUMER_OPEN_FILES: "otelcol_fileconsumer_open_files_ratio",
  OTELCOL_FILECONSUMER_READING_FILES: "otelcol_fileconsumer_reading_files_ratio",
  OTELCOL_OTELSVC_K8S_POD_ADDED: "otelcol_otelsvc_k8s_pod_added_ratio_total",
  OTELCOL_OTELSVC_K8S_POD_TABLE_SIZE: "otelcol_otelsvc_k8s_pod_table_size_ratio",
  OTELCOL_OTELSVC_K8S_POD_UPDATED: "otelcol_otelsvc_k8s_pod_updated_ratio_total",
  OTELCOL_PROCESS_CPU_SECONDS: "otelcol_process_cpu_seconds_total",
  OTELCOL_PROCESS_MEMORY_RSS: "otelcol_process_memory_rss_bytes",
  OTELCOL_PROCESS_RUNTIME_HEAP_ALLOC: "otelcol_process_runtime_heap_alloc_bytes",
  OTELCOL_PROCESS_RUNTIME_TOTAL_ALLOC: "otelcol_process_runtime_total_alloc_bytes_total",
  OTELCOL_PROCESS_RUNTIME_TOTAL_SYS_MEMORY: "otelcol_process_runtime_total_sys_memory_bytes",
  OTELCOL_PROCESS_UPTIME_SECONDS: "otelcol_process_uptime_seconds_total",
  OTELCOL_PROCESSOR_BATCH_SEND_SIZE: "otelcol_processor_batch_batch_send_size",
  OTELCOL_PROCESSOR_BATCH_SIZE_TRIGGER_SEND: "otelcol_processor_batch_batch_size_trigger_send_total",
  OTELCOL_PROCESSOR_BATCH_METADATA_CARDINALITY: "otelcol_processor_batch_metadata_cardinality",
  OTELCOL_PROCESSOR_BATCH_TIMEOUT_TRIGGER_SEND: "otelcol_processor_batch_timeout_trigger_send_total",
  OTELCOL_PROCESSOR_INCOMING_ITEMS: "otelcol_processor_incoming_items_total",
  OTELCOL_PROCESSOR_OUTGOING_ITEMS: "otelcol_processor_outgoing_items_total",
  OTELCOL_RECEIVER_ACCEPTED_LOG_RECORDS: "otelcol_receiver_accepted_log_records_total",
  OTELCOL_RECEIVER_ACCEPTED_METRIC_POINTS: "otelcol_receiver_accepted_metric_points_total",
  OTELCOL_RECEIVER_REFUSED_LOG_RECORDS: "otelcol_receiver_refused_log_records_total",
  OTELCOL_RECEIVER_REFUSED_METRIC_POINTS: "otelcol_receiver_refused_metric_points_total",
  CONDITION_READY_HEALTHY: "condition_ready_healthy",
  CONDITION_READY_MESSAGE: "condition_ready_message",
  CONDITION_READY_REASON: "condition_ready_reason",
  CONTAINER_RESOURCE_CPU_LIMIT: "container_resource_cpu_limit",
  CONTAINER_RESOURCE_CPU_USAGE: "container_resource_cpu_usage",
  CONTAINER_RESOURCE_MEMORY_LIMIT: "container_resource_memory_limit",
  CONTAINER_RESOURCE_MEMORY_USAGE: "container_resource_memory_usage",
  PROMHTTP_METRIC_HANDLER_ERRORS: "promhttp_metric_handler_errors_total",
  TARGET_INFO: "target_info",
} as const;

export const VICTORIA_METRICS = {
  VM_HTTP_REQUESTS_TOTAL: "vm_http_requests_total",
  VM_HTTP_REQUESTS_ALL_TOTAL: "vm_http_requests_all_total",
  VM_HTTP_REQUEST_DURATION_SECONDS_SUM:"vm_http_request_duration_seconds_sum",
  VM_HTTP_REQUEST_DURATION_SECONDS_COUNT: "vm_http_request_duration_seconds_count",
  VM_HTTP_REQUEST_ERRORS_TOTAL: "vm_http_request_errors_total",
  VM_HTTP_CONN_TIMEOUT_CLOSED_CONNS_TOTAL: "vm_http_conn_timeout_closed_conns_total",
  VM_TCPLISTENER_CONNS: "vm_tcplistener_conns",
  VM_TCPLISTENER_READ_BYTES_TOTAL: "vm_tcplistener_read_bytes_total",
  VM_TCPLISTENER_WRITE_BYTES_TOTAL: "vm_tcplistener_written_bytes_total",
  VM_TCPLISTENER_ERRORS_TOTAL: "vm_tcplistener_errors_total",
  VM_TCPLISTENER_ACCEPTS_TOTAL: "vm_tcplistener_accepts_total",
  VM_TCPLISTENER_WRITTEN_BYTES_TOTAL: "vm_tcplistener_written_bytes_total",
  VM_TCPLISTENER_READ_TIMEOUTS_TOTAL: "vm_tcplistener_read_timeouts_total",
  VM_AVAILABLE_CPU_CORES: "vm_available_cpu_cores",
  VL_ERRORS_TOTAL: "vl_errors_total",
  VL_HTTP_ERRORS_TOTAL: "vl_http_errors_total",
  VL_UDP_ERRORS_TOTAL: "vl_udp_errors_total",
  VL_HTTP_REQUESTS_TOTAL: "vl_http_requests_total",
  VL_HTTP_REQUEST_DURATION_SECONDS_SUM: "vl_http_request_duration_seconds_sum",
  VL_UDP_REQESTS_TOTAL: "vl_udp_reqests_total",
  PROCESS_IO_READ_BYTES_TOTAL: "process_io_read_bytes_total",
  PROCESS_IO_WRITTEN_BYTES_TOTAL: "process_io_written_bytes_total",
  PROCESS_IO_READ_SYSCALLS_TOTAL: "process_io_read_syscalls_total",
  PROCESS_IO_WRITE_SYSCALLS_TOTAL: "process_io_write_syscalls_total",
  PROCESS_CPU_SECONDS_TOTAL: "process_cpu_seconds_total",
  PROCESS_CPU_SECONDS_USER_TOTAL: "process_cpu_seconds_user_total",
  PROCESS_CPU_SECONDS_SYSTEM_TOTAL: "process_cpu_seconds_system_total",
  PROCESS_RESIDENT_MEMORY_BYTES: "process_resident_memory_bytes",
  PROCESS_VIRTUAL_MEMORY_BYTES: "process_virtual_memory_bytes",
  PROCESS_MEMORY_LIMIT_BYTES: "process_memory_limit_bytes",
  PROCESS_RESIDENT_MEMORY_PEAK_BYTES: "process_resident_memory_peak_bytes",
  GO_GOROUTINES: "go_goroutines",
  GO_CGO_CALLS_COUNT: "go_cgo_calls_count",
  GO_GOMAXPROCES: "go_gomaxprocs",
  GO_GC_CPU_SECONDS_TOTAL: "go_gc_cpu_seconds_total",
  GO_GC_DURATION_SECONDS: "go_gc_duration_seconds",
  GO_GC_DURATION_SECONDS_COUNT: "go_gc_duration_seconds_count",
  GO_MEMSTATS_HEAP_ALLOC_BYTES: "go_memstats_heap_alloc_bytes",
  GO_MEMSTATS_HEAP_INUSE_BYTES: "go_memstats_heap_inuse_bytes",
  GO_MEMSTATS_HEAP_IDLE_BYTES: "go_memstats_heap_idle_bytes",
  GO_MEMSTATS_HEAP_OBJECTS: "go_memstats_heap_objects",

  VLSELECT_BACKEND_CONNS: "vlselect_backend_conns",
  VLSELECT_BACKEND_DIALS_TOTAL: "vlselect_backend_dials_total",
  VLSELECT_BACKEND_DIAL_ERRORS_TOTAL: "vlselect_backend_dial_errors_total",
  VLSELECT_BACKEND_CONN_BYTES_READ_TOTAL: "vlselect_backend_conn_bytes_read_total",
  VLSELECT_BACKEND_CONN_BYTES_WRITTEN_TOTAL: "vlselect_backend_conn_bytes_written_total",
  VLSELECT_BACKEND_CONN_READ_ERRORS_TOTAL: "vlselect_backend_conn_read_errors_total",
}

export type MetricName = typeof METRICS[keyof typeof METRICS];