{{- if .Values.hmc.installTemplates }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: motel
  namespace: hmc-system
  labels:
    hmc.mirantis.com/managed: "true"
spec:
  url: https://mirantis.github.io/motel/
{{- end }}