{{- if (index .Values "victoriametrics" "vmagent" | default dict).enabled | default false }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  externalLabels:
    clusterName: {{ .Values.global.clusterName }}
  extraArgs:
    promscrape.dropOriginalLabels: "true"
    promscrape.streamParse: "true"
  image:
    tag: v1.105.0
  license: {}
  port: "8429"
  remoteWrite:
  - url: {{ .Values.victoriametrics.vmagent.remoteWriteUrl | quote }}
  scrapeInterval: 20s
  selectAllByDefault: true
{{- end }}