{{- if (index .Values "victoriametrics" "vmalert" | default dict).enabled | default false }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: cluster
  namespace: {{ .Release.Namespace }}
spec:
  configMaps: []
  datasource:
    url: http://vmselect-cluster.mon.svc:8481/select/0/prometheus
  evaluationInterval: 15s
  externalLabels: {}
  extraArgs:
    http.pathPrefix: /
    remoteWrite.disablePathAppend: "true"
  image:
    tag: v1.105.0
  license: {}
  notifiers:
  - url: http://vmalertmanager-cluster-0.vmalertmanager-cluster.mon.svc:9093/
  port: "8080"
  remoteRead:
    url: {{ .Values.victoriametrics.vmalert.remoteRead | default "http://vmselect-cluster.mon.svc:8481/select/0/prometheus" }} 
  remoteWrite:
    url: http://vminsert-cluster.mon.svc:8480/insert/0/prometheus/api/v1/write
  selectAllByDefault: true
{{- end }}