{{- if (index .Values "victoriametrics" "vmauth" | default dict).enabled | default false }}
apiVersion: v1
kind: Secret
metadata:
  name: vmuser-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.victoriametrics.vmauth.credentials.password | default "motel" }}
{{- end }}