{{- if .Values.kcm.installTemplates }}
{{- range $name, $values := .Values.kcm.kof.charts }}
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: kof-{{ $name }}
  namespace: {{ $.Values.kcm.namespace }}
spec:
  helm:
    chartRef:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmChart
      name: kof-{{ $name }}
      namespace: {{ $.Values.kcm.namespace }}
  providers: []
{{- end }}
{{- end }}
