apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  namespace: istio-system
  name: otel-tracing
  annotations:
    helm.sh/hook: post-install
spec:
  tracing:
  - providers:
    - name: otel-tracing
    randomSamplingPercentage: 100