{{- $global := .Values.global | default dict }}
{{- $globalValues := dict }}
{{- $customRegistry := "" }}
{{- if $global.registry }}
  {{- $globalValues = printf `
global:
  registry: $R
  imageRegistry: $R
  image:
    registry: $R
  hub: $R/istio
grafana-operator:
  image:
    repository: $R/grafana/grafana-operator
external-dns:
  image:
    repository: $R/external-dns/external-dns
jaeger-operator:
  image:
    repository: $R/jaegertracing/jaeger-operator
opencost:
  opencost:
    exporter:
      image:
        registry: $R
    ui:
      image:
        registry: $R
opentelemetry-operator:
  manager:
    image:
      repository: $R/opentelemetry-operator/opentelemetry-operator
    collectorImage:
      repository: $R/otel/opentelemetry-collector-contrib
  kubeRBACProxy:
    image:
      repository: $R/brancz/kube-rbac-proxy
opentelemetry-kube-stack:
  defaultCRConfig:
    image:
      repository: $R/opentelemetry-collector-contrib
  cleanupJob:
    image:
      repository: $R/bitnamisecure/kubectl

` | replace "$R" $global.registry | fromYaml }}
  {{- if ne $global.registry "docker.io" }}
    {{- $customRegistry = $global.registry }}
  {{- end }}
{{- end -}}

{{- range $istio := list true false }}
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
{{- if $istio }}
   name: kof-istio-child-cluster
{{- else }}
  name: kof-child-cluster
{{- end }}
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/kof-cluster-role: child
    {{- if $istio }}
      k0rdent.mirantis.com/istio-role: member
    {{- else }}
    matchExpressions:
      - key: "k0rdent.mirantis.com/istio-role"
        operator: DoesNotExist
    {{- end }}

  serviceSpec:
    services:
      {{- $version := $.Chart.Version | replace "." "-" }}

      {{- if and (not $istio) (index $.Values "cert-manager" "enabled") }}
      - name: cert-manager
        namespace: {{ $.Release.Namespace }}
        template: {{ index $.Values "cert-manager" "template" }}
        values: |
          crds:
            enabled: true
        {{- with $customRegistry }}
          image:
            repository: {{ . }}/jetstack/cert-manager-controller
          acmesolver:
            image:
              repository: {{ . }}/jetstack/cert-manager-acmesolver
          cainjector:
            image:
              repository: {{ . }}/jetstack/cert-manager-cainjector
          startupapicheck:
            image:
              repository: {{ . }}/jetstack/cert-manager-startupapicheck
          webhook:
            image:
              repository: {{ . }}/jetstack/cert-manager-webhook
        {{- end }}
      {{- end }}

      - name: kof-operators
        namespace: {{ $.Release.Namespace }}
        template: kof-operators-{{ $version }}
        templateChain: kof-operators-{{ $version }}
        values: |
          {{`{{ $operatorsValuesFromAnnotation := index .Cluster.metadata.annotations "k0rdent.mirantis.com/kof-operators-values" | default "{}" | fromYaml }}`}}
          {{`{{`}} $operatorsValuesFromHelm := `{{ $.Values.operators | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{`}} $globalValuesFromHelm := `{{ $globalValues | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{ mergeOverwrite (dict) $globalValuesFromHelm $operatorsValuesFromHelm $operatorsValuesFromAnnotation | toYaml | nindent 4 }}`}}

      - name: kof-collectors
        namespace: {{ $.Release.Namespace }}
        template: kof-collectors-{{ $version }}
        templateChain: kof-collectors-{{ $version }}
        values: |
        {{- if $istio }}
          {{`{{ $regionalClusterName := getField "ChildConfig" "data.regional_cluster_name" }}`}}
        {{- else }}
          {{`{{ $writeMetricsEndpoint := getField "ChildConfig" "data.write_metrics_endpoint" }}`}}
          {{`{{ $readMetricsEndpoint := getField "ChildConfig" "data.read_metrics_endpoint" }}`}}
          {{`{{ $logsEndpoint := getField "ChildConfig" "data.write_logs_endpoint" }}`}}
          {{`{{ $tracesEndpoint := getField "ChildConfig" "data.write_traces_endpoint" }}`}}
          {{`{{ $vmuserSecretVersion := getField "StorageVMUserCredentials" "metadata.resourceVersion" }}`}}
        {{- end }}
          {{`{{ $collectorsValuesFromAnnotation := index .Cluster.metadata.annotations "k0rdent.mirantis.com/kof-collectors-values" | default "{}" | fromYaml }}`}}
          {{`{{`}} $collectorsValuesFromHelm := `{{ $.Values.collectors | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{`}} $collectorsValuesHere := `
          global:
            clusterName: {childClusterName}
            clusterNamespace: {childClusterNamespace}
          opentelemetry-kube-stack:
            clusterName: {childClusterName}
            collectors:
            {{- if $istio }}
              controller-k0s:
                enabled: false
            {{- end }}
              daemon:
                hostNetwork: {{ not $istio }}
                config:
                  service:
                    extensions:
                      - k8s_observer
                      - file_storage/filelogreceiver
                      - file_storage/filelogsyslogreceiver
                      - file_storage/filelogk8sauditreceiver
                      - file_storage/journaldreceiver
                    {{- if not $istio }}
                      - basicauth/metrics
                      - basicauth/logs
                      - basicauth/traces
                    telemetry:
                      metrics:
                        address: ${env:OTEL_K8S_NODE_IP}:8888
                        readers:
                          - pull:
                              exporter:
                                prometheus:
                                  host: ${env:OTEL_K8S_NODE_IP}
                                  port: 8888
                    {{- end }}
            defaultCRConfig:
            {{- if not $istio }}
              env:
                - name: KOF_VM_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: storage-vmuser-credentials
                - name: KOF_VM_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: storage-vmuser-credentials
                - name: KOF_JAEGER_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: jaeger-admin-credentials
                - name: KOF_JAEGER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: jaeger-admin-credentials
              podAnnotations:
                k0rdent.mirantis.com/kof-vmuser-secret-version: "{vmuserSecretVersion}"
            {{- end }}
              config:
                processors:
                  resource/k8sclustername:
                    attributes:
                    - action: insert
                      key: k8s.cluster.name
                      value: {childClusterName}
                    - action: insert
                      key: k8s.cluster.namespace
                      value: {childClusterNamespace}
              {{- if not $istio }}
                extensions:
                  basicauth/logs:
                    client_auth:
                      username: ${env:KOF_VM_USER}
                      password: ${env:KOF_VM_PASSWORD}
                  basicauth/metrics:
                    client_auth:
                      username: ${env:KOF_VM_USER}
                      password: ${env:KOF_VM_PASSWORD}
                  basicauth/traces:
                    client_auth:
                      username: ${env:KOF_JAEGER_USER}
                      password: ${env:KOF_JAEGER_PASSWORD}
                service:
                  extensions:
                  - basicauth/logs
                  - basicauth/metrics
                  - basicauth/traces
              {{- end }}
                exporters:
                  debug: {}
                  otlphttp/logs:
                  {{- if $istio }}
                    logs_endpoint: http://{regionalClusterName}-logs-insert:9481/insert/opentelemetry/v1/logs
                  {{- else }}
                    logs_endpoint: {logsEndpoint}
                    auth:
                      authenticator: basicauth/logs
                  {{- end }}
                  otlphttp/traces:
                  {{- if $istio }}
                    endpoint: http://{regionalClusterName}-jaeger-collector:4318
                  {{- else }}
                    endpoint: {tracesEndpoint}
                    auth:
                      authenticator: basicauth/traces
                  {{- end }}
                  prometheusremotewrite:
                  {{- if $istio }}
                    endpoint: http://{regionalClusterName}-vminsert:8480/insert/0/prometheus/api/v1/write
                  {{- else }}
                    endpoint: {writeMetricsEndpoint}
                    auth:
                      authenticator: basicauth/metrics
                  {{- end }}
                    external_labels:
                      cluster: {childClusterName}
                      clusterNamespace: {childClusterNamespace}
          opencost:
            opencost:
              prometheus:
              {{- if $istio }}
                existingSecretName: ""
              {{- end }}
                external:
                {{- if $istio }}
                  url: http://{regionalClusterName}-vmselect:8481/select/0/prometheus
                {{- else }}
                  url: {readMetricsEndpoint}
                {{- end }}
              exporter:
                defaultClusterId: {childClusterName}
          ` | replace "{childClusterName}" .Cluster.metadata.name | replace "{childClusterNamespace}" .Cluster.metadata.namespace
          {{- if $istio }} | replace "{regionalClusterName}" $regionalClusterName
          {{- else }} | replace "{tracesEndpoint}" $tracesEndpoint | replace "{logsEndpoint}" $logsEndpoint | replace "{writeMetricsEndpoint}" $writeMetricsEndpoint | replace "{readMetricsEndpoint}" $readMetricsEndpoint | replace "{vmuserSecretVersion}" $vmuserSecretVersion
          {{- end }} | fromYaml {{`}}`}}
          {{`{{`}} $globalValuesFromHelm := `{{ $globalValues | toYaml | nindent 10 }}` | fromYaml {{`}}`}}
          {{`{{ mergeOverwrite (dict) $globalValuesFromHelm $collectorsValuesHere $collectorsValuesFromHelm $collectorsValuesFromAnnotation | toYaml | nindent 4 }}`}}
    templateResourceRefs:
    - identifier: ChildConfig
      resource:
        apiVersion: v1
        kind: ConfigMap
        name: kof-cluster-config-{{`{{ .Cluster.metadata.name }}`}}
        namespace: "{{`{{ .Cluster.metadata.namespace }}`}}"
    - identifier: ChildKCMCluster
      optional: true
      resource:
        apiVersion: cluster.x-k8s.io/v1beta1
        kind: Cluster
        name: "{{`{{ .Cluster.metadata.name }}`}}"
        namespace: "{{`{{ .Cluster.metadata.namespace }}`}}"
    - identifier: ChildSveltosCluster
      optional: true
      resource:
        apiVersion: lib.projectsveltos.io/v1beta1
        kind: SveltosCluster
        name: "{{`{{ .Cluster.metadata.name }}`}}"
        namespace: "{{`{{ .Cluster.metadata.namespace }}`}}"
    - identifier: StorageVMUserCredentials
      optional: true
      resource:
        apiVersion: v1
        kind: Secret
        name: storage-vmuser-credentials
        namespace: {{ $.Release.Namespace }}
{{ end }}