{{- if .Values.kcm.kof.secrets_copy.secrets }}
{{- /* Distributing secrets to clusters automatically*/}}
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: kof-secrets
spec:
  clusterSelector:
    matchLabels: {{ .Values.kcm.kof.secrets_copy.matchLabels | toYaml | nindent 6 }}
  templateResourceRefs:
{{- range .Values.kcm.kof.secrets_copy.secrets }}
    - resource:
        apiVersion: v1
        kind: Secret
        name: {{ . }}
        namespace: {{ $.Release.Namespace }}
      identifier: Resource
{{- end }}
  policyRefs:
    - kind: ConfigMap
      name: copy-resource-template
      namespace: {{ $.Release.Namespace }}
{{- end }}
