{{- if (index .Values "victoriametrics" "vmagent" | default dict).enabled | default false }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-state-metrics
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - honorLabels: true
    metricRelabelConfigs:
    - action: labeldrop
      regex: (uid|container_id|image_id)
    port: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
{{- end }}