{{- if (index .Values "victoriametrics" "vmagent" | default dict).enabled | default false }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: prometheus-node-exporter
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - metricRelabelConfigs:
    - action: drop
      regex: /var/lib/kubelet/pods.+
      source_labels:
      - mountpoint
    port: metrics
  jobLabel: jobLabel
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-node-exporter
{{- end }}