{{- if .Values.hmc.installTemplates }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: hmc-system
  labels:
    hmc.mirantis.com/managed: "true"
spec:
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: hmc-system
  labels:
    hmc.mirantis.com/managed: "true"
spec:
  chart: cert-manager
  interval: 10m0s
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: jetstack
  version: 1.16.1
{{- end }}