{{- if .Values.hmc.installTemplates }}
apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: cert-manager-1-16-1
  namespace: hmc-system
spec:
  helm:
    chartRef:
      apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmChart
      name: cert-manager
      namespace: hmc-system
    chartVersion: 1.16.1
  providers: []
{{- end }}