name: "Build and push docker images"
on:
  push:
    branches:
      - main
    # Don't use `paths: ["kof-operator/**", "docker/opentelemetry-collector-contrib/**"]`
    # as QA needs it for each merge to `main`.

jobs:
  build:
    concurrency:
      group: build-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    name: Build and Unit Test
    runs-on: ${{ github.repository_owner == 'k0rdent' && 'arc-runner-set-k0rdent-public' || 'ubuntu-latest' }}
    outputs:
      version: ${{ steps.vars.outputs.version }}
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Shared setup
        uses: ./.github/actions/shared-setup
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "kof-operator/go.mod"
          cache: false
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "18.18.2"
      - name: Unit tests
        working-directory: ./kof-operator
        run: |
          make test
      - name: Build web application
        working-directory: ./kof-operator
        run: make build-web-app
        # Creates `kof-operator/webapp/collector/dist`
        # which will be embedded at `docker/build-push-action` step.
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get outputs
        id: vars
        run: |
          GIT_VERSION=$(git describe --tags --always)
          echo "version=${GIT_VERSION}" >> $GITHUB_OUTPUT
      - name: Build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean --verbose --snapshot
        run: |
          repo_lower=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          repo=oci://ghcr.io/${repo_lower}/charts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_OPERATOR_REPO: ghcr.io/${{ $repo }}/kof-operator-controller
          IMAGE_OTEL_COLLECTOR_REPO: ghcr.io/${{ $repo }}/kof-opentelemetry-collector-contrib
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
          VERSION: ${{ steps.vars.outputs.version }}
          SKIP_SCM_RELEASE: true
      - name: Push
        run: |
          repo_lower=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          repo=oci://ghcr.io/${repo_lower}/charts
          docker push ghcr.io/${{ $repo }}/kof-operator-controller:${{ steps.vars.outputs.version }}-arm64
          docker push ghcr.io/${{ $repo }}/kof-operator-controller:${{ steps.vars.outputs.version }}-amd64
          docker manifest create \
            ghcr.io/${{ $repo }}/kof-operator-controller:${{ steps.vars.outputs.version }} \
            --amend ghcr.io/${{ $repo }}/kof-operator-controller:${{ steps.vars.outputs.version }}-arm64 \
            --amend ghcr.io/${{ $repo }}/kof-operator-controller:${{ steps.vars.outputs.version }}-amd64
          docker manifest push ghcr.io/${{ $repo }}/kof-operator-controller:${{ steps.vars.outputs.version }}
